/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.lang.Comparable;

public class ArticleTopic implements Comparable<ArticleTopic> {

	private long id = 0;
	private long articleId;
	private long topicId;

	public long getId() {
		return id;
	}

	public long getArticleId() {
		return articleId;
	}

	public long getTopicId() {
		return topicId;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setArticleId(long articleId) {
		 this.articleId = articleId;
	}

	public void setTopicId(long topicId) {
		 this.topicId = topicId;
	}

	public int compareTo(ArticleTopic o) {
		if(articleId!=o.getArticleId()) {
			if(this.articleId < o.getArticleId()) return -1; else return 1;
		}
		if(topicId!=o.getTopicId()) {
			if(this.topicId < o.getTopicId()) return -1; else return 1;
		}
		return 0;
	}

}
