/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.lang.Comparable;
import java.util.Date;

public class Article implements Comparable<Article> {

	private long id = 0;
	private long publicationId;
	private String name = "";
	private String byline = "";
	private String introduction = "";
	private String details = "";
	private String status = "";
	private boolean deleted;
	private boolean published;
	private Date publishedDate = new Date();
	private Date createdDate = new Date();
	private Date lastUpdate = new Date();
	private long lastUpdatePersonId;

	public long getId() {
		return id;
	}

	public long getPublicationId() {
		return publicationId;
	}

	public String getName() {
		return name;
	}

	public String getByline() {
		return byline;
	}

	public String getIntroduction() {
		return introduction;
	}

	public String getDetails() {
		return details;
	}

	public String getStatus() {
		return status;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public boolean isPublished() {
		return published;
	}

	public Date getPublishedDate() {
		return publishedDate;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public long getLastUpdatePersonId() {
		return lastUpdatePersonId;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setPublicationId(long publicationId) {
		 this.publicationId = publicationId;
	}

	public void setName(String name) {
		 this.name = name;
	}

	public void setByline(String byline) {
		 this.byline = byline;
	}

	public void setIntroduction(String introduction) {
		 this.introduction = introduction;
	}

	public void setDetails(String details) {
		 this.details = details;
	}

	public void setStatus(String status) {
		 this.status = status;
	}

	public void setDeleted(boolean deleted) {
		 this.deleted = deleted;
	}

	public void setPublished(boolean published) {
		 this.published = published;
	}

	public void setPublishedDate(Date publishedDate) {
		 this.publishedDate = publishedDate;
	}

	public void setCreatedDate(Date createdDate) {
		 this.createdDate = createdDate;
	}

	public void setLastUpdate(Date lastUpdate) {
		 this.lastUpdate = lastUpdate;
	}

	public void setLastUpdatePersonId(long lastUpdatePersonId) {
		 this.lastUpdatePersonId = lastUpdatePersonId;
	}

	public int compareTo(Article o) {
		if(publicationId!=o.getPublicationId()) {
			if(this.publicationId < o.getPublicationId()) return -1; else return 1;
		}
		if(name.compareTo(o.getName())!=0) {
			return name.compareTo(o.getName());
		}
		if(byline.compareTo(o.getByline())!=0) {
			return byline.compareTo(o.getByline());
		}
		if(introduction.compareTo(o.getIntroduction())!=0) {
			return introduction.compareTo(o.getIntroduction());
		}
		if(details.compareTo(o.getDetails())!=0) {
			return details.compareTo(o.getDetails());
		}
		if(status.compareTo(o.getStatus())!=0) {
			return status.compareTo(o.getStatus());
		}
		if(deleted!=o.deleted) {
			if(this.deleted) return -1; else return 1;
		}
		if(published!=o.published) {
			if(this.published) return -1; else return 1;
		}
		if(publishedDate.compareTo(o.getPublishedDate())!=0) {
			return publishedDate.compareTo(o.getPublishedDate());
		}
		if(createdDate.compareTo(o.getCreatedDate())!=0) {
			return createdDate.compareTo(o.getCreatedDate());
		}
		if(lastUpdate.compareTo(o.getLastUpdate())!=0) {
			return lastUpdate.compareTo(o.getLastUpdate());
		}
		if(lastUpdatePersonId!=o.getLastUpdatePersonId()) {
			if(this.lastUpdatePersonId < o.getLastUpdatePersonId()) return -1; else return 1;
		}
		return 0;
	}

}
