/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.sql.DataSource;
import java.util.List;
import java.util.ArrayList;
import java.io.IOException;
import java.util.Date;

public class ArticleTopicFactory {

    private DataSource dataSource=null;

    public ArticleTopicFactory(DataSource dataSource) {
        this.dataSource = dataSource;
    }
    /**
     * Setup is called during factory initialization to 
     * allow any initialization to be done before this 
     * factory object is used.
     */
    public void setup() throws IOException {

        //Create the database table if it does not exist.
        Connection c=null;
        PreparedStatement s=null;
		try {
			c=dataSource.getConnection();
			s=c.prepareStatement(
				"create table if not exists article_topic (" +
				"id bigint auto_increment primary key,"+
                "article_id bigint,"+
                "topic_id bigint"+
				")DEFAULT CHARSET=utf8 ENGINE=innodb");
            s.execute();
            s.close();
            s=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(!e.toString().contains("ORA-00955")) {
                if(c!=null) { try { c.close(); } catch(Exception f){} }
                throw new IOException(e.toString());
            }
        }

        if(c!=null) { try { c.close(); } catch(Exception f){} }
    }

    /**
     * Post-setup is called when the DAO layer has completed 
     * initalisation of all DAO objects. 
     */
    public void postSetup() throws IOException {

    }

    /**
     * Retrieve an object from the <i>Article Topic</i> data source. 
     */
    public ArticleTopic get(long id) throws IOException {
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        ArticleTopic item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id,article_id,topic_id "+
                "from article_topic " +
                "where id=?");
            s.setLong(1,id);
            results=s.executeQuery();
            if(results.next()) {
                item=new ArticleTopic();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setTopicId(results.getLong(3));
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return item;
    }

    /**
     * Retrieve a list of objects from the <i>Article Topic</i>
     * data source. 
     */
    public List<ArticleTopic> getAll(long index, long limit) throws IOException {
        List<ArticleTopic> list=new ArrayList<ArticleTopic>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, topic_id "+
                "from article_topic " +
                "order by id " +
                "limit "+index+","+limit
                );
            results=s.executeQuery();
            while(results.next()) {
                ArticleTopic item=new ArticleTopic();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setTopicId(results.getLong(3));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Permanently remove an object from the <i>Article Topic</i>
     * data source. 
     */
    public void delete(long id) throws IOException {
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from article_topic "+
                "where id=?");
            s.setLong(1,id);
            s.execute();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

    }

    /**
     * Permanently remove all objects from the <i>Article Topic</i>
     * data source. 
     */
    public void deleteAll() throws IOException {
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement("delete from article_topic"); 
            s.execute();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

    }

    /**
     * Add a new <i>Article Topic</i> object to the data source. 
     */
    public ArticleTopic insert(ArticleTopic item) throws IOException {
        Connection c=null;
        PreparedStatement s=null;

        try {
            c=dataSource.getConnection();

			s=c.prepareStatement(
				"insert into article_topic ("+
					((item.getId()>0)?"id, ":"")+
                    "article_id, "+
                    "topic_id) "+
                "values("+(item.getId()>0?"?,":"")+"?,?)");
			if(item.getId()>0) {
			s.setLong(1,item.getId());
            s.setLong(2,item.getArticleId());
            s.setLong(3,item.getTopicId());
			} else {
            s.setLong(1,item.getArticleId());
            s.setLong(2,item.getTopicId());
			}
            s.execute();
            // Discover the unique id allocated to the new record
            ResultSet r = s.getGeneratedKeys();
            if (r.next()) {
            	item.setId(r.getInt(1));
            }
            r.close();
            r=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            System.err.println("Problem duing inserting into table article_topic. "+
                "article_id="+item.getArticleId()+", "+ 
                "topic_id="+item.getTopicId()+", "+ 
        "");
            throw new IOException(e.toString());
        }

        return item;
    }

    /**
     * Update an object of type <i>Article Topic</i> the 
     * data source. 
     */
    public void update(ArticleTopic item) throws IOException {
        Connection c=null;
        PreparedStatement s=null;

        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "update article_topic set article_id=?, topic_id=? "+
                "where id=?");
            s.setLong(1,item.getArticleId());
            s.setLong(2,item.getTopicId());
            s.setLong(3,item.getId());
            s.execute();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

    }

    /**
     * Count the number of objects from the <i>Article Topic</i>
     * data source. 
     */
    public long countAll() throws IOException {
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        long count=0;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(1) "+
                "from article_topic "
                );
            results=s.executeQuery();
            if(results.next())
                count=results.getLong(1);
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return count;
    }

    /**
     * Retrieve a set from the Article Topic data source
     * matching on articleId topicId. 
     *
     * @param articleId Value to match on Article Id.
     * @param topicId Value to match on Topic Id.
     * @param index Search results should start from this item.
     * @param limit Search results should return at most this many items.
     */
    public List<ArticleTopic> getByArticleIdTopicId(Long articleId, Long topicId,  long index, long limit) throws IOException {
        List<ArticleTopic> list=new ArrayList<ArticleTopic>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        ArticleTopic item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, topic_id "+
                "from article_topic " +
                "where article_id=? and topic_id=? " +
                "order by id " +
                "limit "+index+","+limit
                );
            s.setLong(1,articleId);
            s.setLong(2,topicId);
            results=s.executeQuery();
            while(results.next()) {
                item=new ArticleTopic();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setTopicId(results.getLong(3));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Count number of items in the <i>Article Topic</i> data source
     * matching on Article Id Topic Id. 
     *
     * @param articleId Value to match on Article Id.
     * @param topicId Value to match on Topic Id.
     */
    public long countByArticleIdTopicId(Long articleId, Long topicId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(*)"+
                "from article_topic " +
                "where article_id=? and topic_id=? " +
                "");
            s.setLong(1,articleId);
            s.setLong(2,topicId);
            results=s.executeQuery();
            if(results.next()) {
                total=results.getLong(1);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Delete of item(s) in the Article Topic data source
     * matching on Article Id Topic Id. 
     *
     * @param ArticleId Value to match on Article Id.
     * @param TopicId Value to match on Topic Id.
     */
    public long deleteByArticleIdTopicId(Long articleId, Long topicId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from article_topic " +
                "where article_id=? and topic_id=? " +
                "");
            s.setLong(1,articleId);
            s.setLong(2,topicId);
            s.executeUpdate();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Retrieve a set from the Article Topic data source
     * matching on articleId. 
     *
     * @param articleId Value to match on Article Id.
     * @param index Search results should start from this item.
     * @param limit Search results should return at most this many items.
     */
    public List<ArticleTopic> getByArticleId(Long articleId,  long index, long limit) throws IOException {
        List<ArticleTopic> list=new ArrayList<ArticleTopic>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        ArticleTopic item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, topic_id "+
                "from article_topic " +
                "where article_id=? " +
                "order by id " +
                "limit "+index+","+limit
                );
            s.setLong(1,articleId);
            results=s.executeQuery();
            while(results.next()) {
                item=new ArticleTopic();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setTopicId(results.getLong(3));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Count number of items in the <i>Article Topic</i> data source
     * matching on Article Id. 
     *
     * @param articleId Value to match on Article Id.
     */
    public long countByArticleId(Long articleId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(*)"+
                "from article_topic " +
                "where article_id=? " +
                "");
            s.setLong(1,articleId);
            results=s.executeQuery();
            if(results.next()) {
                total=results.getLong(1);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Delete of item(s) in the Article Topic data source
     * matching on Article Id. 
     *
     * @param ArticleId Value to match on Article Id.
     */
    public long deleteByArticleId(Long articleId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from article_topic " +
                "where article_id=? " +
                "");
            s.setLong(1,articleId);
            s.executeUpdate();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Retrieve a set from the Article Topic data source
     * matching on topicId. 
     *
     * @param topicId Value to match on Topic Id.
     * @param index Search results should start from this item.
     * @param limit Search results should return at most this many items.
     */
    public List<ArticleTopic> getByTopicId(Long topicId,  long index, long limit) throws IOException {
        List<ArticleTopic> list=new ArrayList<ArticleTopic>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        ArticleTopic item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, topic_id "+
                "from article_topic " +
                "where topic_id=? " +
                "order by id " +
                "limit "+index+","+limit
                );
            s.setLong(1,topicId);
            results=s.executeQuery();
            while(results.next()) {
                item=new ArticleTopic();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setTopicId(results.getLong(3));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Count number of items in the <i>Article Topic</i> data source
     * matching on Topic Id. 
     *
     * @param topicId Value to match on Topic Id.
     */
    public long countByTopicId(Long topicId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(*)"+
                "from article_topic " +
                "where topic_id=? " +
                "");
            s.setLong(1,topicId);
            results=s.executeQuery();
            if(results.next()) {
                total=results.getLong(1);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Delete of item(s) in the Article Topic data source
     * matching on Topic Id. 
     *
     * @param TopicId Value to match on Topic Id.
     */
    public long deleteByTopicId(Long topicId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from article_topic " +
                "where topic_id=? " +
                "");
            s.setLong(1,topicId);
            s.executeUpdate();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }


}
