/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.lang.Comparable;

public class IntegerResult implements Comparable<IntegerResult> {

	private long number;

	public long getNumber() {
		return number;
	}

	public void setNumber(long number) {
		 this.number = number;
	}

	public int compareTo(IntegerResult o) {
		if(number!=o.getNumber()) {
			if(this.number < o.getNumber()) return -1; else return 1;
		}
		return 0;
	}

}
