/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.lang.Comparable;
import java.util.Date;

public class Newsletter implements Comparable<Newsletter> {

	private long id = 0;
	private String name = "";
	private String status = "";
	private long version;
	private String number = "";
	private boolean published;
	private boolean deleted;
	private boolean archived;
	private Date lastUpdate = new Date();
	private long lastUpdatePersonId;

	public long getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public String getStatus() {
		return status;
	}

	public long getVersion() {
		return version;
	}

	public String getNumber() {
		return number;
	}

	public boolean isPublished() {
		return published;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public boolean isArchived() {
		return archived;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public long getLastUpdatePersonId() {
		return lastUpdatePersonId;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setName(String name) {
		 this.name = name;
	}

	public void setStatus(String status) {
		 this.status = status;
	}

	public void setVersion(long version) {
		 this.version = version;
	}

	public void setNumber(String number) {
		 this.number = number;
	}

	public void setPublished(boolean published) {
		 this.published = published;
	}

	public void setDeleted(boolean deleted) {
		 this.deleted = deleted;
	}

	public void setArchived(boolean archived) {
		 this.archived = archived;
	}

	public void setLastUpdate(Date lastUpdate) {
		 this.lastUpdate = lastUpdate;
	}

	public void setLastUpdatePersonId(long lastUpdatePersonId) {
		 this.lastUpdatePersonId = lastUpdatePersonId;
	}

	public int compareTo(Newsletter o) {
		if(name.compareTo(o.getName())!=0) {
			return name.compareTo(o.getName());
		}
		if(status.compareTo(o.getStatus())!=0) {
			return status.compareTo(o.getStatus());
		}
		if(version!=o.getVersion()) {
			if(this.version < o.getVersion()) return -1; else return 1;
		}
		if(number.compareTo(o.getNumber())!=0) {
			return number.compareTo(o.getNumber());
		}
		if(published!=o.published) {
			if(this.published) return -1; else return 1;
		}
		if(deleted!=o.deleted) {
			if(this.deleted) return -1; else return 1;
		}
		if(archived!=o.archived) {
			if(this.archived) return -1; else return 1;
		}
		if(lastUpdate.compareTo(o.getLastUpdate())!=0) {
			return lastUpdate.compareTo(o.getLastUpdate());
		}
		if(lastUpdatePersonId!=o.getLastUpdatePersonId()) {
			if(this.lastUpdatePersonId < o.getLastUpdatePersonId()) return -1; else return 1;
		}
		return 0;
	}

}
