/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.lang.Comparable;

public class NewsletterViewCount implements Comparable<NewsletterViewCount> {

	private long id = 0;
	private long newsletterId;
	private long views;

	public long getId() {
		return id;
	}

	public long getNewsletterId() {
		return newsletterId;
	}

	public long getViews() {
		return views;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setNewsletterId(long newsletterId) {
		 this.newsletterId = newsletterId;
	}

	public void setViews(long views) {
		 this.views = views;
	}

	public int compareTo(NewsletterViewCount o) {
		if(newsletterId!=o.getNewsletterId()) {
			if(this.newsletterId < o.getNewsletterId()) return -1; else return 1;
		}
		if(views!=o.getViews()) {
			if(this.views < o.getViews()) return -1; else return 1;
		}
		return 0;
	}

}
