/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.lang.Comparable;

public class NewsletterArticle implements Comparable<NewsletterArticle> {

	private long id = 0;
	private long newsletterId;
	private long articleId;
	private long sortOrder;
	private String type = "";
	private String picture = "";

	public long getId() {
		return id;
	}

	public long getNewsletterId() {
		return newsletterId;
	}

	public long getArticleId() {
		return articleId;
	}

	public long getSortOrder() {
		return sortOrder;
	}

	public String getType() {
		return type;
	}

	public String getPicture() {
		return picture;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setNewsletterId(long newsletterId) {
		 this.newsletterId = newsletterId;
	}

	public void setArticleId(long articleId) {
		 this.articleId = articleId;
	}

	public void setSortOrder(long sortOrder) {
		 this.sortOrder = sortOrder;
	}

	public void setType(String type) {
		 this.type = type;
	}

	public void setPicture(String picture) {
		 this.picture = picture;
	}

	public int compareTo(NewsletterArticle o) {
		if(newsletterId!=o.getNewsletterId()) {
			if(this.newsletterId < o.getNewsletterId()) return -1; else return 1;
		}
		if(articleId!=o.getArticleId()) {
			if(this.articleId < o.getArticleId()) return -1; else return 1;
		}
		if(sortOrder!=o.getSortOrder()) {
			if(this.sortOrder < o.getSortOrder()) return -1; else return 1;
		}
		if(type.compareTo(o.getType())!=0) {
			return type.compareTo(o.getType());
		}
		if(picture.compareTo(o.getPicture())!=0) {
			return picture.compareTo(o.getPicture());
		}
		return 0;
	}

}
