/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.lang.Comparable;

public class Publication implements Comparable<Publication> {

	private long id = 0;
	private String name = "";
	private boolean hasNewsletters;

	public long getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public boolean isHasNewsletters() {
		return hasNewsletters;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setName(String name) {
		 this.name = name;
	}

	public void setHasNewsletters(boolean hasNewsletters) {
		 this.hasNewsletters = hasNewsletters;
	}

	public int compareTo(Publication o) {
		if(name.compareTo(o.getName())!=0) {
			return name.compareTo(o.getName());
		}
		if(hasNewsletters!=o.hasNewsletters) {
			if(this.hasNewsletters) return -1; else return 1;
		}
		return 0;
	}

}
