/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.sql.DataSource;
import java.util.List;
import java.util.ArrayList;
import java.io.IOException;
import java.util.Date;

public class SearchIndexFactory {

	private DataSource dataSource=null;

	public SearchIndexFactory(DataSource dataSource) {
		this.dataSource = dataSource;
	}
	/**
	 * Setup is called during factory initialization to 
	 * allow any initialization to be done before this 
	 * factory object is used.
	 */
	public void setup() throws IOException {

		//Create the database table if it does not exist.
		Connection c=null;
		PreparedStatement s=null;
		try {
			c=dataSource.getConnection();
			s=c.prepareStatement(
				"create table if not exists search_index (" +
				"id bigint auto_increment primary key,"+
				"article_id bigint,"+
				"field_name varchar(100),"+
				"field_value varchar(21000)"+
				")DEFAULT CHARSET=utf8 ENGINE=innodb");
			s.execute();
			s.close();
			s=null;
		} catch(SQLException e) {
			if(s!=null) { try { s.close(); } catch(Exception f){} }
			if(!e.toString().contains("ORA-00955")) {
			if(c!=null) { try { c.close(); } catch(Exception f){} }
				throw new IOException(e.toString());
			}
		}

		if(c!=null) { try { c.close(); } catch(Exception f){} }
	}

	/**
	 * Post-setup is called when the DAO layer has completed 
	 * initalisation of all DAO objects. 
	 */
	public void postSetup() throws IOException {

    }

    /**
     * Retrieve an object from the <i>Search Index</i> data source. 
     */
    public SearchIndex get(long id) throws IOException {
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        SearchIndex item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id,article_id,field_name,field_value "+
                "from search_index " +
                "where id=?");
            s.setLong(1,id);
            results=s.executeQuery();
            if(results.next()) {
                item=new SearchIndex();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setFieldName(results.getString(3));
                item.setFieldValue(results.getString(4));
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return item;
    }

    /**
     * Retrieve a list of objects from the <i>Search Index</i>
     * data source. 
     */
    public List<SearchIndex> getAll(long index, long limit) throws IOException {
        List<SearchIndex> list=new ArrayList<SearchIndex>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, field_name, field_value "+
                "from search_index " +
                "order by id " +
                "limit "+index+","+limit
                );
            results=s.executeQuery();
            while(results.next()) {
                SearchIndex item=new SearchIndex();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setFieldName(results.getString(3));
                item.setFieldValue(results.getString(4));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Permanently remove an object from the <i>Search Index</i>
     * data source. 
     */
    public void delete(long id) throws IOException {
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from search_index "+
                "where id=?");
            s.setLong(1,id);
            s.execute();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

    }

    /**
     * Permanently remove all objects from the <i>Search Index</i>
     * data source. 
     */
    public void deleteAll() throws IOException {
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement("delete from search_index"); 
            s.execute();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

    }

    /**
     * Add a new <i>Search Index</i> object to the data source. 
     */
    public SearchIndex insert(SearchIndex item) throws IOException {
        Connection c=null;
        PreparedStatement s=null;

        try {
            c=dataSource.getConnection();

			s=c.prepareStatement(
				"insert into search_index ("+
					((item.getId()>0)?"id, ":"")+
                    "article_id, "+
                    "field_name, "+
                    "field_value) "+
                "values("+(item.getId()>0?"?,":"")+"?,?,?)");
			if(item.getId()>0) {
			s.setLong(1,item.getId());
            s.setLong(2,item.getArticleId());
            s.setString(3,item.getFieldName());
            s.setString(4,item.getFieldValue());
			} else {
            s.setLong(1,item.getArticleId());
            s.setString(2,item.getFieldName());
            s.setString(3,item.getFieldValue());
			}
            s.execute();
            // Discover the unique id allocated to the new record
            ResultSet r = s.getGeneratedKeys();
            if (r.next()) {
            	item.setId(r.getInt(1));
            }
            r.close();
            r=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            System.err.println("Problem duing inserting into table search_index. "+
                "article_id="+item.getArticleId()+", "+ 
                "field_name="+item.getFieldName()+", "+ 
                "field_value="+item.getFieldValue()+", "+ 
        "");
            throw new IOException(e.toString());
        }

        return item;
    }

    /**
     * Update an object of type <i>Search Index</i> the 
     * data source. 
     */
    public void update(SearchIndex item) throws IOException {
        Connection c=null;
        PreparedStatement s=null;

        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "update search_index set article_id=?, field_name=?, field_value=? "+
                "where id=?");
            s.setLong(1,item.getArticleId());
            s.setString(2,item.getFieldName());
            s.setString(3,item.getFieldValue());
            s.setLong(4,item.getId());
            s.execute();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

    }

	/**
	 * Count the number of objects from the <i>Search Index</i>
	 * data source. 
	 */
	public long countAll() throws IOException {
		Connection c=null;
		PreparedStatement s=null;
		ResultSet results=null;
		long count=0;
		try {
			c=dataSource.getConnection();
			s=c.prepareStatement(
				"select count(1) "+
				"from search_index "
				);
			results=s.executeQuery();
			if(results.next())
				count=results.getLong(1);
			results.close();
			results=null;
			s.close();
			s=null;
			c.close();
			c=null;
		} catch(SQLException e) {
			if(results!=null) { try { results.close(); } catch(Exception f){} }
			if(s!=null) { try { s.close(); } catch(Exception f){} }
			if(c!=null) { try { c.close(); } catch(Exception f){} }
			throw new IOException(e.toString());
		}

		return count;
	}

    /**
     * Retrieve a set from the Search Index data source
     * matching on articleId. 
     *
     * @param articleId Value to match on Article Id.
     * @param index Search results should start from this item.
     * @param limit Search results should return at most this many items.
     */
    public List<SearchIndex> getByArticleId(Long articleId,  long index, long limit) throws IOException {
        List<SearchIndex> list=new ArrayList<SearchIndex>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        SearchIndex item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, field_name, field_value "+
                "from search_index " +
                "where article_id=? " +
                "order by id " +
                "limit "+index+","+limit
                );
            s.setLong(1,articleId);
            results=s.executeQuery();
            while(results.next()) {
                item=new SearchIndex();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setFieldName(results.getString(3));
                item.setFieldValue(results.getString(4));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Count number of items in the <i>Search Index</i> data source
     * matching on Article Id. 
     *
     * @param articleId Value to match on Article Id.
     */
    public long countByArticleId(Long articleId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(*)"+
                "from search_index " +
                "where article_id=? " +
                "");
            s.setLong(1,articleId);
            results=s.executeQuery();
            if(results.next()) {
                total=results.getLong(1);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Delete of item(s) in the Search Index data source
     * matching on Article Id. 
     *
     * @param ArticleId Value to match on Article Id.
     */
    public long deleteByArticleId(Long articleId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from search_index " +
                "where article_id=? " +
                "");
            s.setLong(1,articleId);
            s.executeUpdate();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Retrieve a set from the Search Index data source
     * matching on fieldName. 
     *
     * @param fieldName Value to match on Field Name.
     * @param index Search results should start from this item.
     * @param limit Search results should return at most this many items.
     */
    public List<SearchIndex> getByFieldName(String fieldName,  long index, long limit) throws IOException {
        List<SearchIndex> list=new ArrayList<SearchIndex>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        SearchIndex item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, field_name, field_value "+
                "from search_index " +
                "where field_name=? " +
                "order by id " +
                "limit "+index+","+limit
                );
            s.setString(1,fieldName);
            results=s.executeQuery();
            while(results.next()) {
                item=new SearchIndex();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setFieldName(results.getString(3));
                item.setFieldValue(results.getString(4));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Count number of items in the <i>Search Index</i> data source
     * matching on Field Name. 
     *
     * @param fieldName Value to match on Field Name.
     */
    public long countByFieldName(String fieldName) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(*)"+
                "from search_index " +
                "where field_name=? " +
                "");
            s.setString(1,fieldName);
            results=s.executeQuery();
            if(results.next()) {
                total=results.getLong(1);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Delete of item(s) in the Search Index data source
     * matching on Field Name. 
     *
     * @param FieldName Value to match on Field Name.
     */
    public long deleteByFieldName(String fieldName) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from search_index " +
                "where field_name=? " +
                "");
            s.setString(1,fieldName);
            s.executeUpdate();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Retrieve a set from the Search Index data source
     * matching on fieldValue. 
     *
     * @param fieldValue Value to match on Field Value.
     * @param index Search results should start from this item.
     * @param limit Search results should return at most this many items.
     */
    public List<SearchIndex> getByFieldValue(String fieldValue,  long index, long limit) throws IOException {
        List<SearchIndex> list=new ArrayList<SearchIndex>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        SearchIndex item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, field_name, field_value "+
                "from search_index " +
                "where field_value=? " +
                "order by id " +
                "limit "+index+","+limit
                );
            s.setString(1,fieldValue);
            results=s.executeQuery();
            while(results.next()) {
                item=new SearchIndex();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setFieldName(results.getString(3));
                item.setFieldValue(results.getString(4));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Count number of items in the <i>Search Index</i> data source
     * matching on Field Value. 
     *
     * @param fieldValue Value to match on Field Value.
     */
    public long countByFieldValue(String fieldValue) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(*)"+
                "from search_index " +
                "where field_value=? " +
                "");
            s.setString(1,fieldValue);
            results=s.executeQuery();
            if(results.next()) {
                total=results.getLong(1);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Delete of item(s) in the Search Index data source
     * matching on Field Value. 
     *
     * @param FieldValue Value to match on Field Value.
     */
    public long deleteByFieldValue(String fieldValue) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from search_index " +
                "where field_value=? " +
                "");
            s.setString(1,fieldValue);
            s.executeUpdate();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Retrieve a set from the Search Index data source
     * matching on fieldName articleId. 
     *
     * @param fieldName Value to match on Field Name.
     * @param articleId Value to match on Article Id.
     * @param index Search results should start from this item.
     * @param limit Search results should return at most this many items.
     */
    public List<SearchIndex> getByFieldNameArticleId(String fieldName, Long articleId,  long index, long limit) throws IOException {
        List<SearchIndex> list=new ArrayList<SearchIndex>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        SearchIndex item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, field_name, field_value "+
                "from search_index " +
                "where field_name=? and article_id=? " +
                "order by id " +
                "limit "+index+","+limit
                );
            s.setString(1,fieldName);
            s.setLong(2,articleId);
            results=s.executeQuery();
            while(results.next()) {
                item=new SearchIndex();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setFieldName(results.getString(3));
                item.setFieldValue(results.getString(4));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Count number of items in the <i>Search Index</i> data source
     * matching on Field Name Article Id. 
     *
     * @param fieldName Value to match on Field Name.
     * @param articleId Value to match on Article Id.
     */
    public long countByFieldNameArticleId(String fieldName, Long articleId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(*)"+
                "from search_index " +
                "where field_name=? and article_id=? " +
                "");
            s.setString(1,fieldName);
            s.setLong(2,articleId);
            results=s.executeQuery();
            if(results.next()) {
                total=results.getLong(1);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Delete of item(s) in the Search Index data source
     * matching on Field Name Article Id. 
     *
     * @param FieldName Value to match on Field Name.
     * @param ArticleId Value to match on Article Id.
     */
    public long deleteByFieldNameArticleId(String fieldName, Long articleId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from search_index " +
                "where field_name=? and article_id=? " +
                "");
            s.setString(1,fieldName);
            s.setLong(2,articleId);
            s.executeUpdate();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Retrieve a set from the Search Index data source
     * matching on fieldValue articleId. 
     *
     * @param fieldValue Value to match on Field Value.
     * @param articleId Value to match on Article Id.
     * @param index Search results should start from this item.
     * @param limit Search results should return at most this many items.
     */
    public List<SearchIndex> getByFieldValueArticleId(String fieldValue, Long articleId,  long index, long limit) throws IOException {
        List<SearchIndex> list=new ArrayList<SearchIndex>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        SearchIndex item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, field_name, field_value "+
                "from search_index " +
                "where field_value=? and article_id=? " +
                "order by id " +
                "limit "+index+","+limit
                );
            s.setString(1,fieldValue);
            s.setLong(2,articleId);
            results=s.executeQuery();
            while(results.next()) {
                item=new SearchIndex();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setFieldName(results.getString(3));
                item.setFieldValue(results.getString(4));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Count number of items in the <i>Search Index</i> data source
     * matching on Field Value Article Id. 
     *
     * @param fieldValue Value to match on Field Value.
     * @param articleId Value to match on Article Id.
     */
    public long countByFieldValueArticleId(String fieldValue, Long articleId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(*)"+
                "from search_index " +
                "where field_value=? and article_id=? " +
                "");
            s.setString(1,fieldValue);
            s.setLong(2,articleId);
            results=s.executeQuery();
            if(results.next()) {
                total=results.getLong(1);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Delete of item(s) in the Search Index data source
     * matching on Field Value Article Id. 
     *
     * @param FieldValue Value to match on Field Value.
     * @param ArticleId Value to match on Article Id.
     */
    public long deleteByFieldValueArticleId(String fieldValue, Long articleId) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from search_index " +
                "where field_value=? and article_id=? " +
                "");
            s.setString(1,fieldValue);
            s.setLong(2,articleId);
            s.executeUpdate();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Retrieve a set from the Search Index data source
     * matching on fieldName fieldValue. 
     *
     * @param fieldName Value to match on Field Name.
     * @param fieldValue Value to match on Field Value.
     * @param index Search results should start from this item.
     * @param limit Search results should return at most this many items.
     */
    public List<SearchIndex> getByFieldNameFieldValue(String fieldName, String fieldValue,  long index, long limit) throws IOException {
        List<SearchIndex> list=new ArrayList<SearchIndex>();
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        SearchIndex item=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select id, article_id, field_name, field_value "+
                "from search_index " +
                "where field_name=? and field_value=? " +
                "order by id " +
                "limit "+index+","+limit
                );
            s.setString(1,fieldName);
            s.setString(2,fieldValue);
            results=s.executeQuery();
            while(results.next()) {
                item=new SearchIndex();
                item.setId(results.getLong(1));
                item.setArticleId(results.getLong(2));
                item.setFieldName(results.getString(3));
                item.setFieldValue(results.getString(4));
                list.add(item);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return list;
    }

    /**
     * Count number of items in the <i>Search Index</i> data source
     * matching on Field Name Field Value. 
     *
     * @param fieldName Value to match on Field Name.
     * @param fieldValue Value to match on Field Value.
     */
    public long countByFieldNameFieldValue(String fieldName, String fieldValue) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        ResultSet results=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "select count(*)"+
                "from search_index " +
                "where field_name=? and field_value=? " +
                "");
            s.setString(1,fieldName);
            s.setString(2,fieldValue);
            results=s.executeQuery();
            if(results.next()) {
                total=results.getLong(1);
            }
            results.close();
            results=null;
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(results!=null) { try { results.close(); } catch(Exception f){} }
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }

    /**
     * Delete of item(s) in the Search Index data source
     * matching on Field Name Field Value. 
     *
     * @param FieldName Value to match on Field Name.
     * @param FieldValue Value to match on Field Value.
     */
    public long deleteByFieldNameFieldValue(String fieldName, String fieldValue) throws IOException {
        long total=0;
        Connection c=null;
        PreparedStatement s=null;
        try {
            c=dataSource.getConnection();
            s=c.prepareStatement(
                "delete from search_index " +
                "where field_name=? and field_value=? " +
                "");
            s.setString(1,fieldName);
            s.setString(2,fieldValue);
            s.executeUpdate();
            s.close();
            s=null;
            c.close();
            c=null;
        } catch(SQLException e) {
            if(s!=null) { try { s.close(); } catch(Exception f){} }
            if(c!=null) { try { c.close(); } catch(Exception f){} }
            throw new IOException(e.toString());
        }

        return total;
    }


}
