/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.lang.Comparable;

public class SearchIndex implements Comparable<SearchIndex> {

	private long id = 0;
	private long articleId;
	private String fieldName = "";
	private String fieldValue = "";

	public long getId() {
		return id;
	}

	public long getArticleId() {
		return articleId;
	}

	public String getFieldName() {
		return fieldName;
	}

	public String getFieldValue() {
		return fieldValue;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setArticleId(long articleId) {
		 this.articleId = articleId;
	}

	public void setFieldName(String fieldName) {
		 this.fieldName = fieldName;
	}

	public void setFieldValue(String fieldValue) {
		 this.fieldValue = fieldValue;
	}

	public int compareTo(SearchIndex o) {
		if(articleId!=o.getArticleId()) {
			if(this.articleId < o.getArticleId()) return -1; else return 1;
		}
		if(fieldName.compareTo(o.getFieldName())!=0) {
			return fieldName.compareTo(o.getFieldName());
		}
		if(fieldValue.compareTo(o.getFieldValue())!=0) {
			return fieldValue.compareTo(o.getFieldValue());
		}
		return 0;
	}

}
