/* Generated by DaoGen version 0.1
 *
 * DO NOT EDIT THIS FILE. This file was automatically
 * generated, any changes made to this fill will be
 * lost if the file is re-generated.
 */
package au.edu.unimelb.news.dao;

import java.lang.Comparable;

public class StringResult implements Comparable<StringResult> {

	private String string = "";

	public String getString() {
		return string;
	}

	public void setString(String string) {
		 this.string = string;
	}

	public int compareTo(StringResult o) {
		if(string.compareTo(o.getString())!=0) {
			return string.compareTo(o.getString());
		}
		return 0;
	}

}
